### ISSUE TITLE
[Question] Don't understand how baseRandInt(i + 1) is working ?

### ISSUE THREAD

**Issue by PrateekSonkar** [deestan/randy#16]
Don't understand how baseRandInt(i + 1) is working in method shuffleInplace? Could you please give more insight on it.

**Comment by deestan** [comment]
It's an implementation of Fisher-Yates, described in pseudocode here https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle as

```
-- To shuffle an array a of n elements (indices 0..n-1):
for i from n−1 downto 1 do
     j ← random integer such that 0 ≤ j ≤ i
     exchange a[j] and a[i]
```

The `baseRandInt(i+1)` means "random position up to and including `i`", and selects the element the iterated elements will switch position with.
